### PR TITLE
Add an integration test for flannel-backend=none

### PR DESCRIPTION
**Pull request by manuelbuil**
#### Proposed Changes ####

Add a new test that verifies cluster starts up correclty up to the point where it needs the CNI plugin to continue

#### Types of Changes ####

test

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by rancher-max — APPROVED** [review]

**Review by dereknola — CHANGES_REQUESTED** [review]
This should be a new section to the E2E startup test, no an entirely new test. If this coverage only concerns server, it should just  be an integration test.

**Review by brandond — APPROVED** [review]

**Comment by manuelbuil** [comment]
> This should be a new section to the E2E startup test, not an entirely new test. If this coverage only concerns server, it should just be an integration test.

Really good point. We can verify this by just using one server, so it could be an integration test. I need to learn how to create one though (sorry, I'm probably going to continue bugging you :facepalm: )

**Review by dereknola — DISMISSED** [review]

**Review by dereknola — COMMENTED** [review]
Please add this test to the integration matrix, so it can run in CI. https://github.com/k3s-io/k3s/blob/master/.github/workflows/integration.yaml#L41

**Comment by manuelbuil** [comment]
> Please add this test to the integration matrix, so it can run in CI. https://github.com/k3s-io/k3s/blob/master/.github/workflows/integration.yaml#L41

done!

**Review by brandond — APPROVED** [review]

**Pull request merged**
