### PR TITLE
Upgrade kube-router to v1.5.0

### PR DESCRIPTION
**Pull request by thomasferrandiz**
#### Proposed Changes ####

This PR upgrades the kube-router dependency to v1.5.0.
It points to the k3s-io fork of kube-router because the netpol dual-stack feature is not integrated in upstream yet.

#### Verification ####

There are no new tests but the upgrade should not break anything.

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/5715
#### User-Facing Change ####

```release-note
The embedded network policy controller has been updated to kube-router v1.5.0
```

### CODE REVIEW

**Comment by dereknola** [comment]
This PR is not going to accomplish #5715. We have to update the k3s-io/kube-router to v1.5.0 first.

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
@dereknola it looks good to me? https://github.com/k3s-io/kube-router/tree/k3s-v1.5.0 is present and appears to be what the replace entry is pointing at.

**Comment by dereknola** [comment]
The branch pointed to is now a horrible amalgamation of commits. Why don't we just update the master branch in our kube-router fork, then reapply the dual-stack commits. This is going to be a nightmare to maintain down the line. 
...
This branch is [67 commits ahead](https://github.com/k3s-io/kube-router/compare/cloudnativelabs:kube-router:master...k3s-v1.5.0), [81 commits behind](https://github.com/k3s-io/kube-router/compare/k3s-v1.5.0...cloudnativelabs:kube-router:master) cloudnativelabs:master.

**Review by brandond — CHANGES_REQUESTED** [review]
I probably wouldn't compare it to master, but to the upstream tag that our `-k3s` tag is based on... but honestly that doesn't look good either: https://github.com/k3s-io/kube-router/compare/k3s-v1.5.0...cloudnativelabs:kube-router:v1.5.0

@thomasferrandiz can you rebase the dual-stack changes on top of the most recent upstream branch or tag? This is our normal process for maintaining forks. Pulling the origin into our fork makes for a messy commit log.

**Comment by dereknola** [comment]
@brandond I opened a PR to do that https://github.com/k3s-io/kube-router/pull/17

**Comment by dereknola** [comment]
Okay @thomasferrandiz please update this PR with the commit `a43bcd8511d263855338a2dcc4d7f409c918077b`, I have rebase the v1.5.0 branch to properly track close to upstream, we are now only:
...
This branch is [2 commits ahead](https://github.com/k3s-io/kube-router/compare/cloudnativelabs:kube-router:master...k3s-v1.5.0), [15 commits behind](https://github.com/k3s-io/kube-router/compare/k3s-v1.5.0...cloudnativelabs:kube-router:master) cloudnativelabs:master.
...
Which is much better :)

**Review by dereknola — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
Rebased to fix conflicts

**Comment by brandond** [comment]
CI is green other than s390x which is out due to hardware issues. Merging.

**Pull request merged**
