### PR TITLE
Update to v1.23.12

### PR DESCRIPTION
**Pull request by matttrach**
Signed-off-by: matttrach <matttrach@gmail.com>

### CODE REVIEW

**Review by briandowns — APPROVED** [review]

**Review by luisrojas2 — APPROVED** [review]

**Comment by matttrach** [comment]
[Drone PR CI 4746](https://drone-pr.k3s.io/k3s-io/k3s/4746)

**Review by brandond — APPROVED** [review]

**Comment by matttrach** [comment]
[Drone PR CI 4749](https://drone-pr.k3s.io/k3s-io/k3s/4749)

**Comment by matttrach** [comment]
[Drone PR CI 4751](https://drone-pr.k3s.io/k3s-io/k3s/4751)

**Comment by matttrach** [comment]
[Drone PR CI 4752](https://drone-pr.k3s.io/k3s-io/k3s/4752)

**Comment by matttrach** [comment]
[Drone PR CI 4753](https://drone-pr.k3s.io/k3s-io/k3s/4753)

**Pull request merged**
