### PR TITLE
Convert containerd config.toml.tmpl Linux template to v2 syntax

### PR DESCRIPTION
**Pull request by Kitanotori**
#### Proposed Changes ####

Convert containerd config.toml.tmpl Linux template to v2 syntax

#### Types of Changes ####

Conversion from deprecated syntax

#### Verification ####

Copy the template part to `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl` (assuming default path) and restart k3s.

#### User-Facing Change ####

```release-note
NONE
```

### CODE REVIEW

**Comment by brandond** [comment]
Thanks for the PR! Don't forget to sign your commits for DCO.

At some point we also need to migrate over to the new CRI-standard `certs.d` style configuration for the registries sections: https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration

**Comment by Kitanotori** [comment]
> Thanks for the PR! Don't forget to sign your commits for DCO.

Yea, had some issues with local settings and the signature not being first recognized if just copypasting to the commit message (that's why several rebases and force pushs..).

> At some point we also need to migrate over to the new CRI-standard `certs.d` style configuration for the registries sections: https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration

Yes, that needs more major changes though, so I thought to first just do simple syntax conversion. I confirmed this works and gets rid of the containerd warning.

> Although apparently this new method doesn't include support for credentials, so those will continue to need to live in the config file.

Supporting username & password auth is a must. Not every user can use the cert auth mechanism. I'm surprised this hasn't been taken into account in containerd.

**Comment by Kitanotori** [comment]
@brandond One ARM test is failing. Do you have insight about that?

**Comment by brandond** [comment]
It's a flake caused by our current stable release having a different version of the Traefik helm chart than the forthcoming release. I tried to address that but apparently failed. It's ok to ignore for now.

We're in code freeze for the upstream patch releases, but can merge this after that is done.

**Review by dereknola — APPROVED** [review]
Looks good, pending end of code-freeze.

**Comment by brandond** [comment]
Merging, thanks for the contribution!

**Review by brandond — APPROVED** [review]

**Pull request merged**
