### PR TITLE
Improved cleanup for etcd unit test

### PR DESCRIPTION
**Pull request by dereknola**
Signed-off-by: Derek Nola <derek.nola@suse.com>

#### Proposed Changes ####
Improved the cleanup of etcd after test end, Previously several go routines would continue to run for the life of the testing process.

#### Types of Changes ####
Flaky Test Fix

#### Verification ####
Stress tested by runnig the test on a 90% CPU utilization to slow things down. Was able to get the test to fail consistently before the patch.

#### Linked Issues ####
TBD

#### User-Facing Change ####

```release-note
NONE
```

### CODE REVIEW

**Comment by brandond** [comment]
Is there an easy way to run these in Docker, so that the tests don't fail with `bind: Address already in use` if multiple CI jobs attempt to run the etcd tests at the same time?

**Comment by dereknola** [comment]
When run in GitHub actions, the unit tests run in an isolated VM. Back-ports for removing the unit tests from DRONE (they are currently removed only in master) are being held back till after November releases.

**Comment by dweomer** [comment]
> When run in GitHub actions, the unit tests run in an isolated VM. Back-ports for removing the unit tests from DRONE (they are currently removed only in master) are being held back till after November releases.

If such are still problematic right now for release(s) I am fine with merging those back-ports. But this is merely my opinion, what do other folks think?

**Review by dweomer — APPROVED** [review]
LGTM, thanks @dereknola

**Pull request merged**
