### PR TITLE
[Release-1.28] Redirect error stream to null when checking nm-cloud systemd unit

### PR DESCRIPTION
**Pull request by manuelbuil**
Backport: https://github.com/k3s-io/k3s/pull/8815
Issue: https://github.com/k3s-io/k3s/issues/9145

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
the install script is only served from master, technically this doesn't need to be backported.

**Comment by manuelbuil** [comment]
> the install script is only served from master, technically this doesn't need to be backported.

let me remove it for clarity

**Comment by manuelbuil** [comment]
@brandond we are executing ./validate script in this branch too right? In that case, `install.sh.sha256sum` must be correct or?

**Comment by manuelbuil** [comment]
`install.sh` is only executed from master. We don't need to backport

**Pull request closed without merging**
