### PR TITLE
chore: add new adopter

### PR DESCRIPTION
**Pull request by miworfi**
PITS Global Data Recovery Services

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Comment by cwayne18** [comment]
Thanks so much for this! As a CNCF project we need to ensure that all commits are signed, would you be willing to re-commit with -s so the DCO check passes?

**Comment by cwayne18** [comment]
@miworfi hi there, sorry to bother but we're not able to merge with a failing DCO check (as a CNCF project).  We can either have you force commit with -s to sign, or if you'd prefer I'd be happy to push a PR quickly to get this file updated, either way is fine just let me know!  Thanks again for your contribution!

**Comment by miworfi** [comment]
Dear @cwayne18,

Thank you for letting me know about the issue with the DCO check. I would appreciate it if you could push a PR quickly to get the file updated. Second option sounds great to me.

Thanks again for your help!

Best regards,
@miworfi

**Comment by cwayne18** [comment]
You got it, PR coming right up!

**Pull request closed without merging**
