### PR TITLE
Add gloo manifest and implement --deploy

### PR DESCRIPTION
**Pull request by chanwit**
This commit contains manifest of Gloo chart with its namespace.
Gloo chart is however skipped by default to avoid conflict with Traefik.
This commit also implements `--deploy` to allow like:

  `k3s server --no-deploy=traefik --deploy=gloo`

for skipping the default Traefik and deploy Gloo instead.

### CODE REVIEW

**Comment by chanwit** [comment]
kindly ping @ibuildthecloud

**Comment by ibuildthecloud** [comment]
@chanwit I feel like in the code there should be some type of "conflict map" such that if you deploy gloo we know to automatically remove traefik.

**Comment by CelsoSantos** [comment]
This is not being considered?

**Comment by brandond** [comment]
We have talked a bit about doing some additional work on AddOns, including some sort of slot system where only one component can fill each 'slot' - CNI, Ingress, etc. This would be extended to both K3s and RKE2. I don't have a roadmap date for this though.

**Comment by xiaods** [comment]
the addon chart don't need bundle to k3s

**Comment by dereknola** [comment]
Closing this PR as:
1) Out of date
2) The team has decided not to add native Gloo support as an ingress controller
3) Disabling traefik and installing another ingress controller is natively supported, see https://www.suse.com/support/kb/doc/?id=000020082

**Pull request closed without merging**
