### PR TITLE
Fix confuse func name

### PR DESCRIPTION
**Pull request by xiaods**
#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Comment by briandowns** [comment]
Is the intent here to change the functions to be Hungarian notation?

**Comment by dereknola** [comment]
@xiaods Please fill out the forms for this PR. The point of this PR is not well explained.

**Comment by dweomer** [comment]
@xiaods while I appreciate that the k3s codebase can be confusing your changes as proposed here add needless noise. It is a common idiom in Go to call un-exported (a.k.a. package-private) functions from exported (a.k.a. public) functions such as where pkg/agent/config/config.go `Get()` calls `get()`.

Please see:
- https://go.dev/tour/basics/3
- https://go.dev/doc/effective_go.html

**Comment by xiaods** [comment]
@dweomer thanks for infos.

**Pull request closed without merging**
