### PR TITLE
Avoid redundant chmod of k3s.yaml on startup

### PR DESCRIPTION
**Pull request by allentc**
#### Proposed Changes ####

Server unconditionally[1] performs chmod(2) on /etc/rancher/k3s/k3s.yaml on every startup.  This has a couple site effects that are analyzed in the commit message.

#### Types of Changes ####

Code change to pkg/util/file.go makes chmod happen only if the new mode is different from the current mode.

### CODE REVIEW

**Comment by kralicky** [comment]
I like this change, the setfacl scenario you describe is my preferred way to configure k3s.yaml, and it is rather tedious to fix it every time the server restarts. As a side note I think it would be useful to have some additional options for configuring kubeconfig permissions, like setting a group owner or acl.

**Comment by allentc** [comment]
Re: DCO failure.  The contribution guidelines state the full name should appear in "Signed-off-by:" but the DCO check expects the github username.

**Comment by Oats87** [comment]
> Re: DCO failure. The contribution guidelines state the full name should appear in "Signed-off-by:" but the DCO check appears to expect the github username.

Thanks for the PR. Unfortunately, we will need to have the DCO check pass in order for us to be able to merge this. Most of our devs use the `-s` option on `git commit` which removes questioning from it. For example, my commits end up with:

```
Signed-off-by: Chris Kim <oats87g@gmail.com>
```

contained within them. 

As for the contents of the PR, this looks great and your use case for sure makes sense. I suppose there are specific scenarios where a user may want to clear their file ACLs but would be able to do this using `chmod`. I’m going to hold off giving it the lgtm until the DCO check passes.

**Comment by cjellick** [comment]
broke on the cgroup v2 test @brandond @AkihiroSuda. Any thoughts? Seems like a random download error, but if this is going to be flaky, that concerns me.

**Comment by Oats87** [comment]
> broke on the cgroup v2 test @brandond @AkihiroSuda. Any thoughts? Seems like a random download error, but if this is going to be flaky, that concerns me.

Appears to have been a transient failure, I reran that action and it succeeded this time.

**Review by brandond — APPROVED** [review]

**Comment by allentc** [comment]
Correcting the DCO signature check: Would adding an empty commit with the desired "Signed-off-by: allentc allenc28@yahoo.com" be sufficient?  Or some other remedy?

**Comment by brandond** [comment]
The DCO signoff needs to be in the format
> Signed-off-by: First Last <address@domain.com>

where the address@domain.com is one of the addresses listed for your account at https://github.com/settings/emails

**Comment by allentc** [comment]
Closing this, if possible.  Tests are failing for unknown reasons and I've bungled the DCO check.  I'll try some other time.

**Pull request closed without merging**
