### PR TITLE
Update traefik helm chart and enable http3 support

### PR DESCRIPTION
**Pull request by tete17**
#### Proposed Changes ####

Update the traefik helm chart & enable http3 by default.

Http3 is a greate protocol for edge clusters and content delivery networks. It is one of the selling points of cloudflare as a CDN and could benefit a lot of people to have a quick and simple way to spin up a http3 compliant web server for testing.

#### Types of Changes ####

New features

#### Verification ####

We can simply spin up a k3s docker image and perform a quick curl command against it. We should see 2 things: 
 * The `Alt-Svc` header indicating there is a h3 service under 443
 * http3 requests if you launch it with a modern web browser like chrome.

#### User-Facing Change ####

```release-note
Enable http3 on by default on traefik
```

#### Further Comments ####

I figure this could be a good addition given trafik already automatically enables http2 so why not doing it also for http3

### CODE REVIEW

**Comment by tete17** [comment]
Build seems to be failing because the latest traefik image is not yet mirrored.
Maybe someone with more permissions than me can help me out here :)

**Comment by brandond** [comment]
If you're up for it, you can open a PR to mirror the new image tag by adding an entry to the list at https://github.com/rancher/image-mirror/blob/master/images-list#L282

**Comment by tete17** [comment]
Hi @brandond thanks for the tip, here is the MR: https://github.com/rancher/image-mirror/pull/208

I couldn't opened until now I was AFAIK during the weekend :)

**Comment by brandond** [comment]
The CI failures both look like flakes, so I think you're good to go. I will talk with the team about enabling HTTP3 by default. Perhaps as part of the 1.24 release?

**Comment by dereknola** [comment]
Closing this PR as we updated Traefik to v1.10.14 in this PR: https://github.com/k3s-io/k3s/pull/5135.
Opening an Issue to track adding http3 support in 1.24: https://github.com/k3s-io/k3s/issues/5184

**Pull request closed without merging**
