### PR TITLE
Print error when downloading file error inside install script

### PR DESCRIPTION
**Pull request by if-nil**
#### Proposed Changes ####

When an error occurs in the download function of the installation script, the program will simply exit due to the effect of 'set -e':
``` bash
ubuntu@test:~$ ./install.sh
[INFO]  Finding release for channel stable
[INFO]  Using stable as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
ubuntu@test:~$
```
This change can indicate a download error:
``` bash
ubuntu@test:~$ ./install.sh
[INFO]  Finding release for channel stable
[INFO]  Using stable as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
[ERROR]  Download failed
ubuntu@test:~$
```

#### Types of Changes ####

Bugfix
#### Linked Issues ####
#9154 

#### User-Facing Change ####

```release-note
NONE
```

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Review by brandond — CHANGES_REQUESTED** [review]
This will need to be updated to include the updated install script checksum.

**Comment by vitorsavian** [comment]
@if-nil 

you can use this command here for getting the checksum

```bash
sha256sum install.sh > install.sh.sha256sum
```

and then to verify if it is everything ok with the file

```bash
sha256sum -c install.sh.sha256sum
```

**Comment by vitorsavian** [comment]
Thanks for the changes, but you will now need to sign your commits.

**Comment by if-nil** [comment]
> Thanks for the changes, but you will now need to sign your commits.
> 
> This link could be useful https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

I'm having some problems with sign mycommits, but I'll fix it soon!

**Comment by if-nil** [comment]
@vitorsavian @brandond 
PTAL. commits have been signed, and conflicts have been resolved.

**Review by vitorsavian — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Pull request merged**
