### PR TITLE
Changes local storage pods to have 700 permissions

### PR DESCRIPTION
**Pull request by dereknola**
Signed-off-by: dereknola <derek.nola@suse.com>

#### Proposed Changes ####
Individual storage pods under `/var/lib/rancher/k3s/storage` will now have 0700 permissions to prevent other users from accessing them. 

#### Types of Changes ####
Changed mkdir call in `local-storage.yaml`

#### Verification ####
- Start k3s server
- Create local storage by following rancher guide https://rancher.com/docs/k3s/latest/en/storage/
- Verify that created storage under  `/var/lib/rancher/k3s/storage/` has 0700 permissions

#### Linked Issues ####
https://github.com/k3s-io/k3s/issues/2348

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Review by briandowns — APPROVED** [review]
LGTM

**Comment by flokli** [comment]
This broke all volumes for containers running not as root. See https://github.com/k3s-io/k3s/issues/3704, which reported this as a k3s regression.

From https://github.com/rancher/local-path-provisioner/issues/182#issue-827747922, `/var/lib/rancher/k3s/storage` shouln't be world-readable (but restricted to root), and individual volumes should be chmod 777:

> So volume itself is 0777, but the parent directory secured with 0700 and accessible by root only.

**Comment by brandond** [comment]
@flokli if you look at the bottom of that issue you should see linked PRs for every branch resolving the regression. The fix will be included in the next release.

**Comment by flokli** [comment]
@brandond let's take the discussion over to https://github.com/k3s-io/k3s/issues/2348#issuecomment-891998196.

**Pull request merged**
