### PR TITLE
Update to v1.25.1

### PR DESCRIPTION
**Pull request by matttrach**
Signed-off-by: matttrach <matttrach@gmail.com>

### CODE REVIEW

**Comment by matttrach** [comment]
go mod tidy seems to have updated:
- cel-go
- glog
- ginkgo
- gomega

**Review by dereknola — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Review by galal-hussein — APPROVED** [review]

**Review by luisrojas2 — APPROVED** [review]

**Comment by matttrach** [comment]
Drone CI (failed): https://drone-pr.k3s.io/k3s-io/k3s/4717

**Comment by matttrach** [comment]
Drone CI: https://drone-pr.k3s.io/k3s-io/k3s/4722

**Comment by matttrach** [comment]
Drone passed: https://drone-pr.k3s.io/k3s-io/k3s/4728

**Pull request merged**
