### PR TITLE
Bugfix: honor the -v commandline flag

### PR DESCRIPTION
**Pull request by moio**
#### Proposed Changes ####

Set log level in logrus according to the commandline parameter.

#### Types of Changes ####

Bugfix.

#### Verification ####

 - Install k3s (tested with v1.24.6+k3s1)
 - Run k3s with  the `-v=6` option

#### Testing ####

Only tested manually, only really relevant for developers. Please advise if any kind of automated test is required to get the PR merged.

#### Linked Issues ####

Fixes https://github.com/k3s-io/k3s/issues/6656

#### User-Facing Change ####

```release-note
NONE
```

### CODE REVIEW

**Comment by brandond** [comment]
--debug sets the level for k3s components that use logrus. -v sets the verbosity for klog-based components, such as the various Kubernetes controllers. Do you see a meaningful difference in output with this change?

**Comment by moio** [comment]
> --debug sets the level for k3s components that use logrus. -v sets the verbosity for klog-based components, such as the various Kubernetes controllers. Do you see a meaningful difference in output with this change?

Thanks for explaining, I did not even understand well the context TBH.

My use case is: as a k3s user, I would like to set arbitrary log level for the whole k3s - my current problem is getting trace log lines from kine.

I am open to any suggestions as to change/add commandline flags if this is too hacky.

**Comment by brandond** [comment]
In general trace is too high a level for kine to run at for any significant period of time. If we need trace-level logs from kine for troubleshooting, we usually just run a standalone instance of kine via the binary or docker image, and point K3s at its http endpoint. That also has the benefit of giving us the kine logs separate from the rest of the k3s and kubernetes component logs.

**Comment by moio** [comment]
I am fine closing this if the flag's intent is different and this solution does not align with the intended use case.

**Pull request closed without merging**
