### PR TITLE
cgroup2 CI: add rootless

### PR DESCRIPTION
**Pull request by AkihiroSuda**
#### Proposed Changes ####

Add rootless tests to cgroup2 CI

#### Types of Changes ####

Tests

#### Verification ####

See the result of cgroup2 CI.

Rootless tests are prefixed with `[Rootless]`.

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/2845

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@ibuildthecloud @erikwilson  @dweomer @brandond Could you take a look? Failure in ARM CI seems unrelated.

**Comment by AkihiroSuda** [comment]
(Also, I'd like to get the doc PR https://github.com/rancher/docs/pull/3243 to be reviewed :pray:)

**Comment by brandond** [comment]
All CI is failing, equinix seems to be having network problems and can't reliably pull from GitHub.

**Comment by Oats87** [comment]
@AkihiroSuda I went ahead and re-triggered your CI run.

**Comment by AkihiroSuda** [comment]
Thanks for restarting, CI seems green now

**Review by brandond — APPROVED** [review]

**Review by erikwilson — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Can this (and https://github.com/rancher/docs/pull/3243) be merged?

**Pull request merged**
