### PR TITLE
Update to v1.23.11

### PR DESCRIPTION
**Pull request by matttrach**
Signed-off-by: matttrach <matttrach@gmail.com>

### CODE REVIEW

**Review by luisrojas2 — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by matttrach** [comment]
Drone CI: https://drone-pr.k3s.io/k3s-io/k3s/4719
(failed)

**Comment by matttrach** [comment]
Done CI: https://drone-pr.k3s.io/k3s-io/k3s/4720/1/4
failed - flakey test? restarting

**Comment by matttrach** [comment]
Drone CI: https://drone-pr.k3s.io/k3s-io/k3s/4723/1/2
failed - "no space on device"

**Comment by matttrach** [comment]
sorry, Drone passed: https://drone-pr.k3s.io/k3s-io/k3s/4726

**Pull request merged**
