### PR TITLE
updating to v1.24.6-k3s1

### PR DESCRIPTION
**Pull request by matttrach**
Signed-off-by: matttrach <matttrach@gmail.com>

### CODE REVIEW

**Review by dereknola — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Review by galal-hussein — APPROVED** [review]

**Comment by matttrach** [comment]
https://drone-pr.k3s.io/k3s-io/k3s/4744
failed: 
/tmp/bEaiAq/agents/1/logs/system.log:
"Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache"
"Failed to load kernel module with modprobe, you can ignore this message when kube-proxy is running inside container without mounting /lib/modules"
"Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
"Failed to create listener for podResources endpoint" err="failed to move temporary file to addr ...: invalid cross-device link"

**Comment by matttrach** [comment]
[Drone PR 4745](https://drone-pr.k3s.io/k3s-io/k3s/4745)

**Review by briandowns — APPROVED** [review]

**Comment by matttrach** [comment]
[Drone PR CI 4747](https://drone-pr.k3s.io/k3s-io/k3s/4747)

**Comment by matttrach** [comment]
Drone CI passed, restarting fedora-35 conformance test

**Pull request merged**
