### PR TITLE
Promote v1.23.9+k3s1 to Stable

### PR DESCRIPTION
**Pull request by nikolaishields**
#### Proposed Changes ####

Promote stable version of k3s to 1.23.9+k3s1

#### Types of Changes ####
channel server

#### Testing ####

Install K3s from channel server

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Comment by briandowns** [comment]
Commit needs to be signed.

**Comment by cwayne18** [comment]
I wonder if we can move to 1.24 now? @briandowns @dereknola @brandond any thoughts?

**Comment by brandond** [comment]
I'm +1 on going to 1.24.

**Comment by galal-hussein** [comment]
Closing this in favor of a new PR to stabilize 1.24

**Pull request closed without merging**
