### PR TITLE
Fix cronjob example

### PR DESCRIPTION
**Pull request by akose73**
In the case of "* */5 * * *", it runs every minute past every 5 hours, so it is not true that it runs every 5 hours.
To solve it set 0 as minutes (0 */5 * * *)
Related PR:
https://github.com/rancher/rke2-docs/pull/38

#### Linked Issues ####

* https://github.com/k3s-io/k3s/issues/6752
#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by brandond — APPROVED** [review]
Thanks for the contribution!

**Review by cwayne18 — APPROVED** [review]
Nice catch, thank you! We're currently in a code freeze due to releases, but will merge this as soon as we can!

**Comment by cwayne18** [comment]
Oops I'm sorry @akose73 , as @brandond pointed out please re-commit with -s to make sure the DCO check can pass.  Thanks again!

**Comment by akose73** [comment]
Ohh, so sorry. I signed-off my commit and pushed again.

**Review by dereknola — APPROVED** [review]

**Pull request merged**
