### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by fourstepper**
Fix broken link

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Comment by fourstepper** [comment]
I will not pull this locally to fulfill the DCO, anyone feel free to re-commit this

**Comment by dereknola** [comment]
This is not broken, github will automatically append the "https"

**Comment by fourstepper** [comment]
it doesn't for me...

**Comment by dereknola** [comment]
As author will not complete DCO, closing PR

**Pull request closed without merging**
