### PR TITLE
Update cni plugins version to v1.3.0

### PR DESCRIPTION
**Pull request by manuelbuil**
#### Proposed Changes ####

We released a new rancher/plugins tag last month. k3s should start using it

#### Types of Changes ####

Version bump

#### Verification ####

Just deploy normal k3s and check things are still working

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/8054

#### User-Facing Change ####

```release-note
Upgraded cni-plugins to v1.3.0
```

### CODE REVIEW

**Comment by manuelbuil** [comment]
Still on code freeze, DNM!

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
I think this is also done in the windows agent PR, but that is moving quite slowly so I don't see any reason not to pull it in separately.

**Comment by manuelbuil** [comment]
> I think this is also done in the windows agent PR, but that is moving quite slowly so I don't see any reason not to pull it in separately.

you are right! I missed that. @seanyen are you ok if I do this here?

**Comment by seanyen** [comment]
@manuelbuil please go ahead and update the CNI plugin! Thanks.

**Review by rbrtbnfgl — APPROVED** [review]

**Pull request merged**
