### PR TITLE
Allow Local path provisioner to read helper logs

### LINKED ISSUE #9834: Local path provisioner disallowed from reading Pods logs
**Environmental Info:**
K3s Version: v1.29.3+k3s1
Local path provisioner: v0.0.26

Node(s) CPU architecture, OS, and Version: 
Linux 5.14.0-362.24.1.el9_3.x86_64 https://github.com/k3s-io/k3s/issues/1 SMP PREEMPT_DYNAMIC Wed Mar 20 04:52:13 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, embedded etcd

**Describe the bug:**
If helper pod fails, then Local path provisioner cannot get logs of it.

**Steps To Reproduce:**
1-8. The same as in #9833.
9. Check logs of Local path provisioner. Get error:
```
pods \"helper-pod-delete-pvc-3f2233a9-795e-4ba0-a52f-e4bf335979a4\" is forbidden: User \"system:serviceaccount:kube-system:local-path-provisioner-service-account\" cannot get resource \"pods/log\" in API group \"\" in the namespace \"kube-system\""
```
[local-path-provisioner.log](https://github.com/k3s-io/k3s/files/14808655/local-path-provisioner.log)

**Expected behavior:**
Logs of failed helper pod can be seen in Local path provisioner's logs.

**Actual behavior:**
Error in logs, no logs from child pod.

**Workaround:**
Add permissions to read Pod's logs:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "configmaps", "pods/log"]
    verbs: ["get", "list", "watch"]
```

### PR DESCRIPTION
**Pull request by zc-devs**
#### Proposed Changes ####

Added permissions for Local path provisioner to read helper Pod's logs

#### Types of Changes ####

Bugfix

#### Verification ####

Steps from #9834
Should not be `local-path-provisioner-service-account cannot get resource "pods/log"` error, but logs from helper Pod.

#### Testing ####

Perhaps, no

#### Linked Issues ####

* #9834

#### User-Facing Change ####
```release-note
```

#### Further Comments ####

No

### CODE REVIEW

**Review by brandond — CHANGES_REQUESTED** [review]
Thanks for the contribution!

You also need to run `make download generate` (or run `./scripts/download` and then `go generate`) to update the generated bindata that embeds these files into the binary.

**Review by brandond — CHANGES_REQUESTED** [review]
Only the `zz_generated_bindata.go` should have changed; I'm not sure where the unrelated whitespace changes came from. Can you remove the other files from this PR?

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
Last thing - please sign-off your commits for DCO!

**Review by dereknola — DISMISSED** [review]

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
Rebased

**Review by dereknola — APPROVED** [review]

**Pull request merged**
