### PR TITLE
remove hidden attribute from cluster flags and related code

### PR DESCRIPTION
**Pull request by briandowns**
#### Proposed Changes ####

Unhides cluster flags from server subcommand and removes related unused code.

#### Types of Changes ####

Unhide server subcommand flags.

#### Linked Issues ####

https://github.com/rancher/rke2/issues/856

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
We should probably delete https://github.com/k3s-io/k3s/blob/master/pkg/cli/cmds/nocluster.go and drop the `!no_etcd` tag from https://github.com/k3s-io/k3s/blob/master/pkg/cluster/etcd.go. I checked through the codebase and we're not using the `no_etcd` build tag either here or in RKE2.

**Review by galal-hussein — APPROVED** [review]
LGTM

**Comment by cjellick** [comment]
dont merge until we have an explanation for why this flag was dropped https://github.com/rancher/rke2/issues/856#issuecomment-815167532

**Comment by brandond** [comment]
@galal-hussein can you confirm that these were unintentionally hidden when attempting to hide the etcd-only related flags (--disable-apiserver, --disable-controller-manager, etc)?

**Comment by galal-hussein** [comment]
> @galal-hussein can you confirm that these were unintentionally hidden when attempting to hide the etcd-only related flags (`--disable-apiserver`, `--disable-controller-manager`, etc)?

Yes I can confirm that they were unintentionally hidden along with the disable cluster flags

**Comment by briandowns** [comment]
Is this ready to merge?

**Comment by brandond** [comment]
@galal-hussein confirmed so I think we're good to go.

**Comment by briandowns** [comment]
Agreed. @cjellick this pass muster with you?

**Pull request merged**
