### PR TITLE
Add Getdeck Beiboot to Adopters

### PR DESCRIPTION
**Pull request by Schille**

### CODE REVIEW

**Review by briandowns — APPROVED** [review]

**Review by VestigeJ — APPROVED** [review]
LGTM

**Comment by cwayne18** [comment]
This is lovely, I hate to ask but can you please re-commit with -s to make the DCO check pass

**Comment by cwayne18** [comment]
Sorry, as a CNCF project we can't merge PR's with a failing DCO check, if you're okay with it @Schille I can add this into a PR I'm working on now to get it added?

**Comment by cwayne18** [comment]
Sorry I didn't wait for your answer before merging, but I did give you a shoutout @Schille! thanks again for this, but I'll close this out for now

**Comment by Schille** [comment]
Thank you @cwayne18 I'm sorry, this slipped my mind.

**Comment by cwayne18** [comment]
No worries! Happens to me all the time 😄 thanks again for the addition!

**Pull request closed without merging**
