### PR TITLE
[release-1.31] Update Kubernetes to v1.31.2

### PR DESCRIPTION
**Pull request by brooksn**
#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by cwayne18 — APPROVED** [review]

**Review by dereknola — APPROVED** [review]

**Comment by dereknola** [comment]
@brooksn if you want to get rid of the single CVE, upstream has also bumped the otelgrpc version to `v0.46.0`. The etcd version we use also links to `v0.46.0`, and upstream k8s is already on `v0.53.0`

Otherwise we will pick it up next month.

**Review by brandond — APPROVED** [review]

**Review by nicholasSUSE — COMMENTED** [review]
Approved

**Pull request merged**
