### PR TITLE
Add topologySpreadConstraints to support scaling of coredns

### PR DESCRIPTION
**Pull request by marcbachmann**
#### Proposed Changes ####
The coredns service is not highly available by default. It is possible to set the replication count to 2, but even then, pods might be scheduled on the same nodes. Adding a `topologySpreadConstraint` distributes the containers on different nodes.

#### Types of Changes ####
Add `topologySpreadConstraints` declaration to coredns deployment spec.

#### Verification ####
Scale the coredns deployment and check whether the pods are distributed on different nodes.

#### Linked Issues ####
https://github.com/k3s-io/k3s/issues/1606

#### User-Facing Change ####
NONE

### CODE REVIEW

**Comment by marcbachmann** [comment]
Sorry, I'm not sure why the build is failing. Tried to run `mkdir -p build/data && ./scripts/download && go generate`, but now there's another error.

**Comment by brandond** [comment]
it looks like you're missing the tools to properly generate the bindata via `./scripts/download && go generate`. Ensure that you have yq installed, and are running the script on a Ubuntu based system so that the gzip content matches that output by CI.

**Comment by marcbachmann** [comment]
Ok, now it succeded on ubuntu.
There were some diffs of traefik and some build args comments I didn't include in the commit: 
image

**Comment by brandond** [comment]
That's. It something I've seen before. What version of go are you using?

**Comment by marcbachmann** [comment]
go version go1.17.1 linux/amd64

started using `docker run -v $PWD:$PWD -w=$PWD -it --rm golang:1.17.1-bullseye bash`

**Comment by brandond** [comment]
Ah, that might be it - Kubernetes is still using 1.16.8; can you try with that?

**Comment by marcbachmann** [comment]
Now I got the correct output without those new annotations 👍 
Still some tar diffs of traefik. But they might be related to something else. This PR would be ready.

**Review by brandond — APPROVED** [review]

**Review by ekrem95 — APPROVED** [review]

**Review by dweomer — APPROVED** [review]

**Review by galal-hussein — APPROVED** [review]

**Comment by brandond** [comment]
Thanks for the contribution!

**Pull request merged**
