### PR TITLE
Update Kube-router ACCEPT rule insertion and install script to clean rules before start 

### PR DESCRIPTION
**Pull request by rbrtbnfgl**
#### Proposed Changes ####

Updated Kube-router version to add the default `ACCEPT` iptables rules right after the latest kubernetes rules to fix setup where a firewall that adds `DROP` rules is enabled.
Updated `install.sh` script to clean the iptables rules before K3s start.

#### Linked Issues ####

#7203 #7244 #7251

#### User-Facing Change ####

```release-note
The embedded kube-router controller has been updated to fix a regression that caused traffic from pods to be blocked by any default drop/deny rules present on the host. Users should still confirm that any externally-managed firewall rules explicitly allow traffic to/from pod and service networks, but this returns the old behavior that was relied upon by some users.
```

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by rbrtbnfgl** [comment]
It seems that `opensuse-leap` test doesn't like `iptables` on the install script.
Does it right to keep the command there or not?

**Comment by brandond** [comment]
I was a little concerned about that. I see that we already have it in the uninstall script, but expecting it to be present at install time is probably not reasonable. Maybe just add a check to see if `iptables` and `ip6tables` exist before calling them?

**Review by brandond — APPROVED** [review]

**Comment by rbrtbnfgl** [comment]
Can I merge it even if it fails during s390 build?

**Comment by brandond** [comment]
I would say yes, go for it.

**Pull request merged**
