### PR TITLE
Update to v1.23.17-k3s1

### PR DESCRIPTION
**Pull request by matttrach**

### CODE REVIEW

**Review by brandond — CHANGES_REQUESTED** [review]
Don't forget to bump golang to track with upstream, at https://github.com/k3s-io/k3s/blob/master/Dockerfile.dapper#L1 and other places.

**Comment by brandond** [comment]
Also looks like the `v1.23.17-k3s1` tag is missing from k3s-io/k3s, although we have `staging/src/k8s.io/api/v1.23.17-k3s1` and all the other staging tags.

**Comment by matttrach** [comment]
good catch! added

**Comment by matttrach** [comment]
looks like go mod needed to be tidied

**Review by dereknola — APPROVED** [review]

**Review by briandowns — APPROVED** [review]

**Pull request merged**
