### PR TITLE
Update install.sh to recommend current version of k3s-selinux

### PR DESCRIPTION
**Pull request by Klaas-**
Signed-off-by: Klaas Demter <re4il07t@duck.com>

#### Proposed Changes ####
During testing an airgapped install I noticed that it was recommending installing a very old version of k3s-selinux. Update the hint to install a current version.

#### Types of Changes ####
Bugfix

#### Verification ####
Hint now shows a current k3s-selinux version during install

#### Linked Issues ####
The version suggested here creates issues with a current version of container-selinux ( https://github.com/k3s-io/k3s-selinux/pull/24#issuecomment-943779675 )

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Comment by cwayne18** [comment]
Thanks so much for the PR! Would you mind signing your commit with -s to make sure the DCO check passes?

**Comment by Klaas-** [comment]
> Thanks so much for the PR! Would you mind signing your commit with -s to make sure the DCO check passes?

done

**Comment by cwayne18** [comment]
Appreciate it! We're in a code freeze currently for the November releases, but the moment it's thawed we'll take a look. Thanks again!

**Review by matttrach — COMMENTED** [review]
Confirmed that is the correct semver for the release marked latest:
https://github.com/k3s-io/k3s-selinux/releases/tag/v1.2.stable.2

**Review by brandond — APPROVED** [review]

**Pull request merged**
