### PR TITLE
Add adr for vpn integration

### PR DESCRIPTION
**Pull request by manuelbuil**
Signed-off-by: Manuel Buil <mbuil@suse.com>

### CODE REVIEW

**Comment by brandond** [comment]
@manuelbuil I'm still excited to see some VPN coordinator integration, if you ever get back to this ;)

**Comment by manuelbuil** [comment]
> @manuelbuil I'm still excited to see some VPN coordinator integration, if you ever get back to this ;)

I have the code ready but I am reluctant to create the PR as I'll be gone for 4 months... not sure what to do, do it now or wait 4 months

**Review by matttrach — APPROVED** [review]
I think this is great, I have been using tailscale for my infra and have had no problems

**Comment by cwayne18** [comment]
@manuelbuil can we revive this?

**Comment by manuelbuil** [comment]
> @manuelbuil can we revive this?

The ADR is part of my other PR, the one that also contains the code: https://github.com/k3s-io/k3s/pull/7352

**Comment by cwayne18** [comment]
@manuelbuil ah got it, so should we close this one out? or is this a pre-req?

**Comment by manuelbuil** [comment]
Closing since the adr got merged with the code

**Pull request closed without merging**
