### PR TITLE
Update embedded kube-router

### PR DESCRIPTION
**Pull request by dereknola**
Signed-off-by: dereknola <derek.nola@suse.com>

#### Proposed Changes ####
Update the embedded kube-router files to the latest commit. Added in new files and tests as necessary.

#### Types of Changes ####
Bugfix

#### Verification ####
For issue https://github.com/k3s-io/k3s/issues/3258, a new iptables rule can be seen:
- Start up k3s server
- `$ iptables-save`
- Should see a new rule:
`-A KUBE-ROUTER-INPUT -m comment --comment "rule to explicitly ACCEPT traffic that comply to network policies" -m mark --mark 0x20000/0x20000 -j ACCEPT`

#### Linked Issues ####
For #3373
Related issue: #3258
Relates issue: #3535

### CODE REVIEW

**Review by brandond — APPROVED** [review]
🎉🎉🎉

I moved the linked issues into Peer Review and the 1.22.0 milestone

**Comment by brandond** [comment]
Looks like it needs a `go mod tidy`?

**Comment by brandond** [comment]
For the logging stuff, I had intentionally replaced it with klog v1 in order to avoid pulling in an additional module version; is there any reason we need to add klog/v2?

**Comment by brandond** [comment]
Apparently codespell learned some new words. I have a fix for that rolled in over at https://github.com/k3s-io/k3s/pull/3553

**Review by briandowns — APPROVED** [review]

**Comment by xiaods** [comment]
need resolve go.mod conflicting case

**Review by brandond — APPROVED** [review]

**Pull request merged**
