### PR TITLE
Bump up github.com/containerd/stargz-snapshotter (v0.11.0)

### PR DESCRIPTION
**Pull request by ktock**
#### Proposed Changes ####

Bump up github.com/containerd/stargz-snapshotter to the latest (v0.11.0)

#### Types of Changes ####

Updating the dependency.

#### Verification ####

Please refer to release notes at https://github.com/containerd/stargz-snapshotter/releases.

#### Linked Issues ####
https://github.com/k3s-io/k3s/issues/5066

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by dereknola — APPROVED** [review]

**Review by briandowns — APPROVED** [review]

**Comment by ktock** [comment]
Thank you for the review. Rebased.

**Review by brandond — APPROVED** [review]

**Comment by ktock** [comment]
Thank you for the review. Rebased and made CI green.

**Comment by brandond** [comment]
February releases just went out, will merge when CI is green.

**Comment by ktock** [comment]
Thank you for the review. Rebased and CI is green.

**Pull request merged**
