### PR TITLE
[release-1.25] Update to v1.25.16

### PR DESCRIPTION
**Pull request by johnatasr**
#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by manuelbuil** [comment]
Why did you drop the go version update in the end?

**Comment by johnatasr** [comment]
@manuelbuil version v1.25 in upstream is not using go 1.20.11, I got an error in drone due the go dump
image

**Comment by manuelbuil** [comment]
> @manuelbuil version v1.25 in upstream is not using go 1.20.11, I got an error in drone due the go dump image

Aaaah ok! I thought that all "maintained" upstream kubernetes versions used the same go version

**Review by manuelbuil — APPROVED** [review]

**Comment by brandond** [comment]
> I thought that all "maintained" upstream kubernetes versions used the same go version

Same, that is a bit unexpected, but I guess since the branch is technically EOL they are backporting only the bare minimum of change for the CVE.

**Pull request merged**
