### PR TITLE
allow coredns override extensions

### PR DESCRIPTION
**Pull request by andrewroffey**
#### Proposed Changes ####

Allow CoreDNS override extensions in default Corefile

Other K8s implementations such as AKS[1] and DigitalOcean[2] have similar configuration

This would enable ConfigMaps to adjust the CoreDNS settings without creating a whole copy of coredns.yaml.

1: https://learn.microsoft.com/en-us/azure/aks/coredns-custom
2: https://docs.digitalocean.com/products/kubernetes/how-to/customize-coredns/

#### Types of Changes ####

New Feature

#### Verification ####

1. Patch Corefile with `import /etc/coredns/custom/*.override` in the `.:53` default server block
2. Create a `coredns-custom` ConfigMap with some custom settings for the default server block, e.g. `rewrite name substring svc.example.com svc.cluster.local`
3. Restart CoreDNS pod
4. Test that the custom config has taken effect. For my example, run `nslookup my-pod.my-svc.my-namespace.svc.example.com` or `getent hosts ...` in a pod and confirm it resolves to the same name as `my-pod.my-svc.my-namespace.svc.cluster.local`

#### Linked Issues ####

* https://github.com/k3s-io/k3s/issues/7639

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by brandond — CHANGES_REQUESTED** [review]
Thanks for the PR! You need to `make download generate` and check in the resulting changes.

**Comment by cwayne18** [comment]
Also as a CNCF project we need to have commits signed, can you please make sure to commit with `-s` so the DCO check passes?  Thanks a lot for the PR!

**Comment by andrewroffey** [comment]
Thanks for checking @cwayne18 @brandond. I've just updated the commit with my signature and checked in the re-generated Go artifact.

**Comment by brandond** [comment]
@andrewroffey your commits are signed (--gpg-sign), but not signed off (--signoff). CLA requires signoff, not signature.

**Comment by andrewroffey** [comment]
> @andrewroffey your commits are signed (-S/--gpg-sign), but not signed off (-s/--signoff). DCO requires signoff, not signature.

@brandond oops, third time lucky, TIL about the -s flag. I've updated that with both this time.

**Review by brandond — APPROVED** [review]

**Review by dereknola — APPROVED** [review]
We are still in code freeze for May releases, but this will get in after that, should be in all June releases.

**Comment by cwayne18** [comment]
Thanks a lot for the PR, and for signing your commits :) Like Derek said we'll get this in as soon as code freeze is thawed

**Comment by andrewroffey** [comment]
Cheers! That's just around the corner, sounds great.

**Pull request merged**
