### PR TITLE
Move Documentation into K3s Repo (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by dereknola**
#### Proposed Changes ####
Move the documentation on K3s currently hosted by Rancher under `rancher/docs` directly into the K3s repo.
Use `mkdocs` with the `material` theme to generate documentation website

#### Verification ####
`mkdocs serve`
- Check all links (both internal and external) work and that all formatting is converted to `mkdocs` format as appropriate (content tabs and page titles being the biggest culprits)

#### Linked Issues ####
TBD

#### User-Facing Change ####

```release-note

```

#### Further Comments ####
Followed the same idea as the RKE2 repo in terms of framework and design.

### CODE REVIEW

**Comment by sirredbeard** [comment]
@dereknola Does this modify where the docs are displayed or just where the backend docs are hosted? In other words, does this move them from docs.rancher.com to k3s.io?

**Comment by Oats87** [comment]
Does it really make sense to be trying to shove the docs into the `k3s-io/k3s` repo? 

Seems that we'll be unnecessarily triggering CI for simple docs updates. I'm a bigger fan of just throwing these docs into `k3s-io/docs` or something like that.

**Comment by dereknola** [comment]
@Oats87 I am totally fine with moving the docs to a separate repo under the k3s-io org, not embedding them in K3s itself. I just know that its weird that the docs are still within the rancher org.

**Comment by dereknola** [comment]
@sirredbeard This PR will do neither of those things. It is simply copying the docs to a new location. There will need to be additional PRs in the rancher/docs repo and likely in the backend rancherlabs/k3s-website repo to point to the new docs location. 

Ideally, after all PRs are done, hosting the website can still be done by rancher, but the docs themselves will sit within k3s-io and the url will be docs.k3s.io and not rancher.com. Similar to how RKE2 Docs are done now. The hosting is rancher, the location is within the rke2 repo itself, and the website is docs.rke2.io

**Comment by sirredbeard** [comment]
@dereknola Thank you for that clarification. Are you leading on those other PRs or do we need to loop in web and EIO?

**Comment by dereknola** [comment]
I am not leading those, we do need to loop in web and EIO.

**Comment by dereknola** [comment]
After discussion with the team, this PR is being closed. Instead, I have opened a new PR to move the k3s docs to a dedicated k3s-io/docs repo. https://github.com/k3s-io/docs/pull/1

**Pull request closed without merging**
