### PR TITLE
Bump spegel to v0.0.20-k3s1

### PR DESCRIPTION
**Pull request by dereknola**
Signed-off-by: Derek Nola <derek.nola@suse.com>

#### Proposed Changes ####
- New spegel version, upstream incorporated more of our patches, ~so we are down from 5 patches to 3 patches~ But we added more :upside_down_face: . 
- Bumps libp2p, making https://github.com/k3s-io/k3s/pull/9719 redundant
- Removes `quic-go` pins. The indirect version is now v0.42.0 (because we bumped libp2p), which resolves the CVE we originally pinned avoid. 

#### Types of Changes ####
Dependency Bump

#### Verification ####
CI Green

#### Linked Issues ####
https://github.com/k3s-io/k3s/issues/7151

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Comment by brandond** [comment]
https://github.com/k3s-io/spegel/compare/v0.0.18-k3s4...v0.0.19-k3s1

LGTM!

**Comment by brandond** [comment]
We might have to revert this one: https://github.com/k3s-io/spegel/commit/8a5978f0d165a7ba6e34fb6dca75ae71cb644be2 in favor of https://github.com/k3s-io/spegel/commit/8fbe436b21588193c9233b6a84c13cd8f15bdad2

I don't agree with his approach to fixing the error handling.

**Comment by dereknola** [comment]
Okay I can work on a patch bringing that back and put out a `k3s2`

**Comment by brandond** [comment]
yeah, probably just revert + cherry-pick should do it.

**Comment by brandond** [comment]
Now there's another one! https://github.com/spegel-org/spegel/releases/tag/v0.0.20

**Comment by dereknola** [comment]
Welp, looks like its a high severity CVE on quic-go

**Review by brandond — APPROVED** [review]

**Review by vitorsavian — APPROVED** [review]

**Pull request merged**
