### PR TITLE
Update klipper-lb image version

### PR DESCRIPTION
**Pull request by manuelbuil**
#### Proposed Changes ####

Update klipper-lb image version to `v0.4.6`

#### Types of Changes ####

Version bump

#### Verification ####

Verify that klipper-lb image works by deploying a service of type external

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/9487

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Comment by brandond** [comment]
Appears there may be something wrong with the new image:
```
  svclb-traefik-4fadc231-4f5fh
  Expected
      <string>: CrashLoopBackOff
  to equal
      <string>: Running
```

**Comment by manuelbuil** [comment]
> Appears there may be something wrong with the new image:
> 
> ```
>   svclb-traefik-4fadc231-4f5fh
>   Expected
>       <string>: CrashLoopBackOff
>   to equal
>       <string>: Running
> ```
> 
> It works OK for me locally, but is consistently failing the e2e tests; I'm not sure why.

I'll investigate when I finish the multus integration

**Comment by manuelbuil** [comment]
Error identified and valid. Great work CI! It can't find iptables in OS using iptables-legacy as default (e.g. what CI uses, Ubuntu 20). Probably the reason is that Alpine 3.19 switched to iptables-nft by default. Need more investigation

**Comment by brandond** [comment]
I suspect we need to add iptables-legacy to https://github.com/k3s-io/klipper-lb/blob/master/package/Dockerfile#L5

**Comment by manuelbuil** [comment]
> I suspect we need to add iptables-legacy to https://github.com/k3s-io/klipper-lb/blob/master/package/Dockerfile#L5

Yes, that''s probably the best solution. `x-tables-legacy-multi` does not exist in 3.19 (after installing iptables), that's why it fails. The entry script requires it. I'm going to create a PR and once merged, I'll create `v0.4.7` and declare `v0.4.6` broken

**Comment by manuelbuil** [comment]
https://github.com/k3s-io/klipper-lb/pull/64

**Review by brandond — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Review by dereknola — APPROVED** [review]

**Pull request merged**
