### PR TITLE
[release-1.19] Backport add etcd backup restore s3

### PR DESCRIPTION
**Pull request by briandowns**
#### Proposed Changes ####

Backports the 3 changes that introduce Etcd snapshot functionality, S3 integration, and Bootstrap storage bug fixes.

### CODE REVIEW

**Comment by xiaods** [comment]
need fix it asap

**Comment by xiaods** [comment]
go: finding module for package k8s.io/kubernetes/pkg/controlplane                                                                                                                 
github.com/xiaods/k8e/pkg/daemons/control/deps imports                                                                                                                            
        k8s.io/kubernetes/pkg/controlplane: module k8s.io/kubernetes@latest found (v1.20.4, replaced by github.com/k3s-io/kubernetes@v1.19.8-k3s1), but does not contain package k
8s.io/kubernetes/pkg/controlplane

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
LGTM except Arm is being fussy again

**Review by galal-hussein — APPROVED** [review]
LGTM

**Pull request merged**
