### PR TITLE
Bump k3s-root to v0.13.0

### PR DESCRIPTION
**Pull request by dereknola**
Signed-off-by: Derek Nola <derek.nola@suse.com>

#### Proposed Changes ####
- Bump k3s-root to latest version

#### Types of Changes ####
Dependency bump

#### Verification ####
CI Green

#### Linked Issues ####
TBD

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by manuelbuil — APPROVED** [review]

**Comment by manuelbuil** [comment]
What if I create an updatecli policy to have this done automatically for the next releases?

**Review by brandond — APPROVED** [review]

**Comment by cwayne18** [comment]
@manuelbuil please do!

**Comment by manuelbuil** [comment]
> @manuelbuil please do!

emojis don't ping me and I forgot about this! Lemme do something quick

**Comment by manuelbuil** [comment]
BTW, we can still merge this one! And updatecli can take care of the next one

**Comment by manuelbuil** [comment]
https://github.com/k3s-io/k3s/pull/9844

**Pull request merged**
