### PR TITLE
Small updates to CONTRIBUTING

### PR DESCRIPTION
**Pull request by davidnuzik**
#### Proposed Changes ####

Small changes to CONTRIBUTING.md

#### Types of Changes ####

Non-breaking change in docs.

#### Verification ####

Review PR content, ensure looks good and makes sense.

#### Linked Issues ####

Not required - small docs change.

#### User-Facing Change ####

```release-note
NONE
```

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by cwayne18** [comment]
Very very small nit, but there is a user facing change here

**Comment by brandond** [comment]
We don't call out docs changes in our release notes, so I would agree with there not being any user-facing change

**Comment by cwayne18** [comment]
Why don't we?

**Review by briandowns — APPROVED** [review]

**Comment by brandond** [comment]
Because docs are only served off master and don't produce a release artifact.

**Pull request merged**
