### PR TITLE
Fix incorrect defer usage

### PR DESCRIPTION
**Pull request by iyear**
Problem:
Using defer inside a loop can lead to resource leaks

Solution:
Close files in the closure

Signed-off-by: iyear <ljyngup@gmail.com>

### CODE REVIEW

**Review by brandond — CHANGES_REQUESTED** [review]
Thanks for the PR! 

It would probably be more clear to just move the loop body into a named function. Adding an anonymous inline function just to make the defer function properly is less clear, over all.

**Comment by iyear** [comment]
I forgot to add comments, I'll add it later.

**Review by brandond — APPROVED** [review]
LGTM. Currently not merging anything until after the releases are cut.

**Review by dereknola — APPROVED** [review]
@iyear Thanks for the community PR!

**Pull request merged**
