### PR TITLE
Capture all fedora atomic variants in install script

### PR DESCRIPTION
**Pull request by dereknola**
#### Proposed Changes ####
- As suggested in the linked issue, instead of adding a VARIANT_ID for every flavor of [fedora atomic ](https://fedoraproject.org/atomic-desktops/) just look and see if this is fedora and a ostree (i.e. rpm-ostree) package manager is available. 

#### Verification ####
Tested on a `kinoite`,  the EOL `fedora Atomic` and `coreos` VMs. 

#### Linked Issues ####
https://github.com/k3s-io/k3s/issues/9361

#### User-Facing Change ####

```release-note
Allow easier installation of k3s on all variants of fedora atomic that use rpm-ostree
```

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by AdamNowotny** [comment]
Just tested this on Bluefin. It doesn't work unless the ID checks are replaced with ID_LIKE.
I created a similar PR (#11167) that checks for ID and VARIANT instead but happy to go with this as long as we can check ID_LIKE. Would that break on other systems?
```
# cat /etc/os-release 
NAME="Bluefin"
VERSION="40.20241021.0 (Silverblue)"
ID=bluefin
ID_LIKE="fedora"
VERSION_ID=40
VERSION_CODENAME="Archaeopteryx"
PLATFORM_ID="platform:f40"
PRETTY_NAME="Bluefin-dx 40 (FROM Fedora Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:universal-blue:bluefin:40"
DEFAULT_HOSTNAME="bluefin"
HOME_URL="https://projectbluefin.io"
DOCUMENTATION_URL="https://docs.projectbluefin.io"
SUPPORT_URL="https://github.com/ublue-os/bluefin/issues/"
BUG_REPORT_URL="https://github.com/ublue-os/bluefin/issues/"
SUPPORT_END=2025-05-13
VARIANT="Silverblue"
VARIANT_ID=bluefin-dx-nvidia
OSTREE_VERSION='40.20241021.0'
BUILD_ID="78bbc1a"
```

**Comment by dereknola** [comment]
@AdamNowotny I've updated the PR to cover Bluefin. We do appreciate your PR,  which is the 3rd such PR we have seen around fedora atomic derived OSes. I'm hoping to "cover everything" with this PR going forward rather than having other future PRs pop up with more VARIANT_IDs.

**Comment by AdamNowotny** [comment]
@dereknola  Just tested this branch and looks good on Bluefin now. I'll close my PR.

**Review by brandond — APPROVED** [review]

**Review by cwayne18 — APPROVED** [review]

**Review by VestigeJ — APPROVED** [review]
LGTM

**Review by briandowns — APPROVED** [review]

**Pull request merged**
