### PR TITLE
Remove otelgrpc pinned dependency

### PR DESCRIPTION
**Pull request by dereknola**
#### Proposed Changes ####
- Unpin otelgrpc dependency, added with the v1.26.0 release, to allow it to match upstreams version automatically.
- Bump grpc to match upstream version

#### Types of Changes ####
Dependency bumps

#### Verification ####
make passes

#### Testing ####
N/A

#### Linked Issues ####
N/A

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by brandond — APPROVED** [review]
if it works great, the otel stuff has been a pain in the but to keep in sync across the different projects.

**Review by brandond — APPROVED** [review]

**Review by vitorsavian — APPROVED** [review]

**Review by cwayne18 — APPROVED** [review]

**Review by galal-hussein — APPROVED** [review]

**Comment by dereknola** [comment]
hmmm... rerunning a failed trivy scan does not seem to work out

**Pull request merged**
