### PR TITLE
Add 1.24 release channel

### PR DESCRIPTION
**Pull request by onedr0p**
#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
Don't forget to sign your commit for DCO!

**Comment by onedr0p** [comment]
Done.

**Comment by onedr0p** [comment]
Should I also bump stable to 1.23.7?

**Comment by onedr0p** [comment]
@brandond any thoughts?

**Review by dereknola — APPROVED** [review]

**Comment by onedr0p** [comment]
Any update?

**Comment by cwayne18** [comment]
Sorry for the delay and we appreciate the PR; we're currently in a code freeze for release so we're just waiting for some final validations before we land any new PRs

**Pull request merged**
