### PR TITLE
[Release-1.22] Add certificate rotation integration tests

### PR DESCRIPTION
**Pull request by galal-hussein**
Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by briandowns — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by dereknola** [comment]
@galal-hussein you need to change the package to `rancher/k3s` we haven't backported the `k3s-io` change.

**Comment by brandond** [comment]
It'll also need the timeout extended as in https://github.com/k3s-io/k3s/pull/5431

**Comment by galal-hussein** [comment]
> @galal-hussein you need to change the package to `rancher/k3s` we haven't backported the `k3s-io` change.

Fixed

**Comment by dereknola** [comment]
The contents of this PR have been merged in https://github.com/k3s-io/k3s/pull/5761

**Pull request closed without merging**
