### PR TITLE
Fix iptables check when sbin isn't in user PATH

### PR DESCRIPTION
**Pull request by NordMike**
#### Proposed Changes ####

Function has_working_xtables() checks presence of iptables under a regular user and then tries to use it under the root. But there are systems where some tools are excluded from regular user environment. So presence of iptables should be checked under the root user.

#### Types of Changes ####

Bugfix

#### Verification ####

I've checked this in Debian 11.

#### Linked Issues ####

* https://github.com/k3s-io/k3s/issues/9438

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Comment by dereknola** [comment]
I would actually argue for the reverse, remove SUDO from both of the commands. Its is either assuumed that the user is root, or has run install with root priveleged  i.e. `curl -sfL https://get.k3s.io | sudo sh -`

**Comment by NordMike** [comment]
> I would actually argue for the reverse, remove SUDO from both of the commands. Its is either assuumed that the user is root, or has run install with root priveleged i.e. `curl -sfL https://get.k3s.io | sudo sh -`

It could be the solution if $SUDO would be removed not only in this place but from around 40 other lines too.

**Comment by NordMike** [comment]
Now sudo is used all over the script. Diverting in this one specific place would be a change of expected behaviour.

**Review by brandond — APPROVED** [review]

**Review by brandond — CHANGES_REQUESTED** [review]
lgtm, but you need to update the checksum file.

**Comment by NordMike** [comment]
Done.

**Comment by NordMike** [comment]
@brandond Is it ok now?

**Review by brandond — APPROVED** [review]

**Review by galal-hussein — APPROVED** [review]

**Pull request merged**
