### PR TITLE
Fix typo in terraform/README.md

### PR DESCRIPTION
**Pull request by eltociear**
#### Proposed Changes ####
creat -> create

#### Types of Changes ####
Fixed typo.

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by cwayne18** [comment]
Thanks for this!  Can you please make sure to sign commits with `git commit -s`?  As a CNCF project we need to make sure that all PR's are signed for the DCO check.  Thanks again!

**Comment by eltociear** [comment]
@cwayne18 

I'm sorry, I made a mistake in the procedure.
Therefore, I will create a new PR.

**Comment by cwayne18** [comment]
No need to apologize! Thanks again for contributing!

**Comment by eltociear** [comment]
@cwayne18 Thanks!!

**Pull request closed without merging**
