### PR TITLE
Flag to disable local load balancer for api server

### PR DESCRIPTION
**Pull request by Negashev**
#### Proposed Changes ####

Allows agents to connect directly to the API without using a local load balancer.

#### Types of Changes ####

enhancement

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Comment by brandond** [comment]
Can you better explain the use case for this? K3s and RKE2 both rely on having agents use the local load-balancer to provide HA for the supervisor and apiservers.

**Comment by Negashev** [comment]
@brandond 
Api under load balancer,

database <- k3s server (api only) (n) <- https load balancer (with domain) <- k3s agent(n)

**Comment by jacksgt** [comment]
Hello @brandond ,

I'm also interested in this feature - here's my use-case:

I have deployed the k3s control plane inside a firewalled environment.
To get access to the (HTTP) API, I'm using an HAProxy reverse proxy with virtual hosts to route the requests to the API.
This setup works fine with regular API access through kubectl:

```sh
$ sed -i "s|server: https://127.0.0.1:6443|server: https://${HOSTNAME}|" k3s.yaml
$ kubectl --kubeconfig=k3s.yaml cluster-info
Kubernetes control plane is running at https://${HOSTNAME}
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

However, because the k3s agent launches an L4 loadbalancer locally and requests from the agent are going to `https://127.0.0.1:6444/cacerts` (instead of `https://${HOSTNAME}/cacerts`).
While k3s' local loadbalancer correctly forwards this request to HAProxy, it is now missing the hostname information (as part of the HTTP Host header), hence HAProxy cannot perform it's routing with vhosts.

By disabling the local loadbalancer (inside k3s agent), I'm hoping that the k3s agent (and it's components) will directly talk to the K3s control plane API at `https://${HOSTNAME}`.

I'm also happy to rebase this PR / open a new one.

**Comment by jacksgt** [comment]
@k3s-dev Could someone kindly take a look at this PR?

**Comment by brandond** [comment]
I am not personally interested in supporting this option, as having the agent components use the local load-balancer tunnel to communicate with all available servers is a core bit of the k3s architecture. I will defer to other members of the team though.

**Comment by dereknola** [comment]
@jacksgt Thank you for taking the time to rebase and maintain this PR. However, after team discussion, we have decided not to move forward with this feature. How K3s agents talk to servers is a key part of the K3s design and changing it is not on the table at this time.

**Pull request closed without merging**
