### PR TITLE
CI: update Fedora 34 -> 36

### PR DESCRIPTION
**Pull request by AkihiroSuda**
#### Proposed Changes ####

Update Fedora 34 to 36.

Fedora 34 has reached EOL on 2022-06-07 
https://docs.fedoraproject.org/en-US/releases/eol/

#### Types of Changes ####

CI

#### Verification ####

Observe the CI result

#### Testing ####

Observe the CI result

#### Linked Issues ####

🚫 

#### User-Facing Change ####

🚫 
#### Further Comments ####

🚫

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Review by dereknola — APPROVED** [review]

**Comment by brandond** [comment]
This works fine for me locally, I'm not sure why it's failing in GH Actions.

**Comment by brandond** [comment]
@dereknola do you know of a good way to get the conformance test to output more information when it fails? It works fine locally for me, and the output that we do get isn't really enough to troubleshoot with.

```
    cgroup-unified: Waiting for deployment "coredns" rollout to finish: 0 of 1 updated replicas are available...
    cgroup-unified: 
    cgroup-unified: real	8m20.007s
    cgroup-unified: user	0m3.903s
    cgroup-unified: sys	0m3.069s
The SSH command responded with a non-zero exit status.
```

**Comment by dereknola** [comment]
Its all just bash scripts, you would need to modify https://github.com/AkihiroSuda/k3s/blob/fedora-36/tests/cgroup/unified/fedora-36/Vagrantfile#L85 to output more info on detecting an `exit != 0`

**Comment by dereknola** [comment]
Locally testing this, I'm still not sure why fedora-36 is broken, it pass just fine on my machine. I did test with `fedora-35` on GH and that passes locally and on CI. So for now we can just move to fedora-35 instead. Yes it EOL in November, but that gives us more time to fix fedora-36.

**Comment by AkihiroSuda** [comment]
> Locally testing this, I'm still not sure why fedora-36 is broken, it pass just fine on my machine. I did test with `fedora-35` on GH and that passes locally and on CI. So for now we can just move to fedora-35 instead. Yes it EOL in November, but that gives us more time to fix fedora-36.

Sure, opened https://github.com/k3s-io/k3s/pull/5996

**Comment by dereknola** [comment]
Closing this PR as we went with updating to 35 instead.

**Pull request closed without merging**
