### PR TITLE
[Release-1/22] changing package to k3s-io

### PR DESCRIPTION
**Pull request by dereknola**
Backport of https://github.com/k3s-io/k3s/pull/4846 to release-1.22

Added output of `pkg/generated` files to dapper, enable `make generate` to actually regenerate those files.
https://github.com/k3s-io/k3s/pull/5585/files#diff-3598233dce47ce9c207a77a9f23394d45235397dd66d7dd9de909487e1bd8e8a

Verification:
`make`

### CODE REVIEW

**Comment by brandond** [comment]
I can't remember why, but I thought we'd decided against backporting the name change. Is the codegen broken if we don't rename?

**Comment by brandond** [comment]
I can't remember why, but I thought we'd decided against backporting the name change. Is the codegen broken if we don't rename?

**Comment by dereknola** [comment]
No, we just delayed back-porting it because we wanted to make sure everything was stable and nothing broke from the master change. Then releases came around again and so we put it on hold till after code freeze and it got forgotten.

**Review by brandond — APPROVED** [review]
Fantastic, this will make some of my other backports much easier!

**Pull request merged**
