### PR TITLE
Update to v1.31.1-k3s1 and Go 1.22.6

### PR DESCRIPTION
**Pull request by briandowns**

### CODE REVIEW

**Review by tashima42 — APPROVED** [review]

**Comment by dereknola** [comment]
The panic is not super helpful
```
panic: close of closed channel

goroutine 17228 [running]:
k8s.io/apiserver/pkg/server.SetupSignalContext()
	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apiserver@v1.31.1-k3s1/pkg/server/signal.go:41 +0x1e
k8s.io/apiserver/pkg/server.SetupSignalHandler()
	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apiserver@v1.31.1-k3s1/pkg/server/signal.go:34 +0x13
k8s.io/kubernetes/cmd/kube-scheduler/app.runCommand.func1()
	/go/pkg/mod/github.com/k3s-io/kubernetes@v1.31.1-k3s1/cmd/kube-scheduler/app/server.go:148 +0x1c
created by k8s.io/kubernetes/cmd/kube-scheduler/app.runCommand in goroutine 377
	/go/pkg/mod/github.com/k3s-io/kubernetes@v1.31.1-k3s1/cmd/kube-scheduler/app/server.go:147 +0x19c
```

**Comment by brandond** [comment]
@galal-hussein ran into that early on; we had to fix it with some changes to our Kubernetes patches for v1.30.0. Did something happen to those when rebasing our patches from v1.30.0 to v1.30.1?

**Comment by brandond** [comment]
@briandowns did you rebase v1.31.0-k3s3 on to v1.31.1, or did you perhaps use the patches from v1.31.0-k3s1 or v1.31.0-k3s2? It kinda looks like some of the problems from the earlier tags are showing up here again.

**Comment by briandowns** [comment]
Yeah, working through things. I'll ask for reviews when it's ready for review.

**Pull request closed without merging**
