### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by H3RSKO**
Fixed typo in readme

 
Proposed changes
======

Types of changes
======

Verification
======

Linked Issues
======
 

Further comments
======

Signed-off-by: H3RSKO <yosefherskovitz@gmail.com>

### CODE REVIEW

**Comment by brandond** [comment]
Thanks for the patch! In order to pass DCO, your commit message needs to include signoff with an address that is valid for your GitHub account.

**Comment by H3RSKO** [comment]
Does this work?

**Comment by brandond** [comment]
No, you need to `git commit --amend --signoff` and then `git push --force-with-lease`

**Comment by H3RSKO** [comment]
Updated.

Thank you Brad!

**Review by brandond — APPROVED** [review]

**Comment by dereknola** [comment]
Closing as this was fixed with https://github.com/k3s-io/k3s/pull/3048

**Pull request closed without merging**
